# Generated by Django 6.0.5 on 2026-05-19 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField()),
                ('service_address', models.TextField()),
                ('special_instructions', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='pending', max_length=15)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_reason', models.TextField(blank=True)),
                ('hirer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings_as_hirer', to=settings.AUTH_USER_MODEL)),
                ('servant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='servants.servantprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
