# Generated by Django 6.0.5 on 2026-05-19 05:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_bn', models.CharField(blank=True, max_length=100)),
                ('icon', models.CharField(default='fa-hands-helping', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#FF6B6B', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ServantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_rate', models.DecimalField(decimal_places=2, default=500.0, max_digits=8)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('availability_status', models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('off', 'Off Duty')], default='available', max_length=15)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('total_jobs', models.PositiveIntegerField(default=0)),
                ('skills', models.TextField(blank=True, help_text='Comma-separated skills')),
                ('location', models.CharField(blank=True, max_length=200)),
                ('nid_number', models.CharField(blank=True, max_length=20)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='servant_profile', to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(related_name='servants', to='servants.servicecategory')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hirer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_reviews', to=settings.AUTH_USER_MODEL)),
                ('servant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='servants.servantprofile')),
            ],
            options={
                'unique_together': {('servant', 'hirer')},
            },
        ),
    ]
